version: '3.8'

services:
  google-workspace-mcp:
    image: b3tts32/google_workspace_mcp:2025.07.30-3
    container_name: google-workspace-mcp
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - google-workspace-network

networks:
  google-workspace-network:
    driver: bridge 